In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
pd.pandas.set_option("display.max_columns", None)

Missing value handel

In [42]:
df=pd.read_csv("Visadataset.csv")

In [43]:
Feature_with_na=[feature for feature in df.columns if df[feature].isnull().sum()>1]
Feature_with_na

[]

In [44]:
duplicate=df.duplicated().sum()
int(duplicate)

0

In [45]:
df.drop("case_id",axis=1,inplace=True)

In [46]:
from datetime import datetime

d=datetime.today()
year=d.year

In [47]:
df.head()

,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [48]:
df["company_age"]=year-df["yr_of_estab"]
# df.head()

In [49]:
cat_column=[column for column in df.columns if df[column].dtype=="O"]
num_column=[column for column in df.columns if df[column].dtype!="O"]

In [50]:
df.drop('yr_of_estab', inplace=True, axis=1)

In [51]:
X=df.drop("case_status",axis=1)
Y=df["case_status"]

In [52]:
X

,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,company_age
0,Asia,High School,N,N,14513,West,592.2029,Hour,Y,19
1,Asia,Master's,Y,N,2412,Northeast,83425.6500,Year,Y,24
2,Asia,Bachelor's,N,Y,44444,West,122996.8600,Year,Y,18
3,Asia,Bachelor's,N,N,98,West,83434.0300,Year,Y,129
4,Africa,Master's,Y,N,1082,South,149907.3900,Year,Y,21
...,...,...,...,...,...,...,...,...,...,...
25475,Asia,Bachelor's,Y,Y,2601,South,77092.5700,Year,Y,18
25476,Asia,High School,Y,N,3274,Northeast,279174.7900,Year,Y,20
25477,Asia,Master's,Y,N,1121,South,146298.8500,Year,N,116
25478,Asia,Master's,Y,Y,1918,West,86154.7700,Year,Y,139
25479,Asia,Bachelor's,Y,N,3195,Midwest,70876.9100,Year,Y,66

In [53]:
Y=np.where(Y=="Denied",1,0)

In [54]:
num_column.remove("yr_of_estab")

In [56]:
discrete_features=[feature for feature in num_column if len(df[feature].unique())<=25]
print('Num of Discrete Features :',len(discrete_features))

Num of Discrete Features : 0

In [57]:
continue_features=[feature for feature in num_column if feature not in discrete_features]
continue_features

['no_of_employees', 'prevailing_wage', 'company_age']

In [58]:
X

,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,company_age
0,Asia,High School,N,N,14513,West,592.2029,Hour,Y,19
1,Asia,Master's,Y,N,2412,Northeast,83425.6500,Year,Y,24
2,Asia,Bachelor's,N,Y,44444,West,122996.8600,Year,Y,18
3,Asia,Bachelor's,N,N,98,West,83434.0300,Year,Y,129
4,Africa,Master's,Y,N,1082,South,149907.3900,Year,Y,21
...,...,...,...,...,...,...,...,...,...,...
25475,Asia,Bachelor's,Y,Y,2601,South,77092.5700,Year,Y,18
25476,Asia,High School,Y,N,3274,Northeast,279174.7900,Year,Y,20
25477,Asia,Master's,Y,N,1121,South,146298.8500,Year,N,116
25478,Asia,Master's,Y,Y,1918,West,86154.7700,Year,Y,139
25479,Asia,Bachelor's,Y,N,3195,Midwest,70876.9100,Year,Y,66

In [59]:
skew=X[continue_features].skew(axis=0,skipna=True)
skew

no_of_employees    12.265260
prevailing_wage     0.755776
company_age         2.037301
dtype: float64

In [60]:
l=["no_of_employees","company_age"]

In [61]:
X

,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,company_age
0,Asia,High School,N,N,14513,West,592.2029,Hour,Y,19
1,Asia,Master's,Y,N,2412,Northeast,83425.6500,Year,Y,24
2,Asia,Bachelor's,N,Y,44444,West,122996.8600,Year,Y,18
3,Asia,Bachelor's,N,N,98,West,83434.0300,Year,Y,129
4,Africa,Master's,Y,N,1082,South,149907.3900,Year,Y,21
...,...,...,...,...,...,...,...,...,...,...
25475,Asia,Bachelor's,Y,Y,2601,South,77092.5700,Year,Y,18
25476,Asia,High School,Y,N,3274,Northeast,279174.7900,Year,Y,20
25477,Asia,Master's,Y,N,1121,South,146298.8500,Year,N,116
25478,Asia,Master's,Y,Y,1918,West,86154.7700,Year,Y,139
25479,Asia,Bachelor's,Y,N,3195,Midwest,70876.9100,Year,Y,66

In [62]:
from sklearn.preprocessing import PowerTransformer
pt=PowerTransformer()
X_copy=pt.fit_transform(X[l])
X_copy=pd.DataFrame(X_copy,columns=l)
X_copy.head()

   no_of_employees  company_age
0         1.517300    -0.958506
1         0.030912    -0.470816
2         2.885076    -1.080479
3        -1.343550     1.632700
4        -0.432287    -0.741917

In [63]:
X

,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,company_age
0,Asia,High School,N,N,14513,West,592.2029,Hour,Y,19
1,Asia,Master's,Y,N,2412,Northeast,83425.6500,Year,Y,24
2,Asia,Bachelor's,N,Y,44444,West,122996.8600,Year,Y,18
3,Asia,Bachelor's,N,N,98,West,83434.0300,Year,Y,129
4,Africa,Master's,Y,N,1082,South,149907.3900,Year,Y,21
...,...,...,...,...,...,...,...,...,...,...
25475,Asia,Bachelor's,Y,Y,2601,South,77092.5700,Year,Y,18
25476,Asia,High School,Y,N,3274,Northeast,279174.7900,Year,Y,20
25477,Asia,Master's,Y,N,1121,South,146298.8500,Year,N,116
25478,Asia,Master's,Y,Y,1918,West,86154.7700,Year,Y,139
25479,Asia,Bachelor's,Y,N,3195,Midwest,70876.9100,Year,Y,66

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,1.517300,-0.958506,0.386667,-1.398537,-0.651230
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,3.0,0.030912,-0.470816,-0.142282,0.169835,-0.533211
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,2.885076,-1.080479,1.694984,0.919079,-0.674834
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,-1.343550,1.632700,-0.243429,0.169994,1.945186
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,3.0,-0.432287,-0.741917,-0.200417,1.428604,-0.604022

In [64]:
# Create Column Transformer with 3 types of transformers
or_columns = ['has_job_experience','requires_job_training','full_time_position','education_of_employee']
oh_columns = ['continent','unit_of_wage','region_of_employment']
transform_columns= ['no_of_employees','company_age']

from sklearn.preprocessing import OneHotEncoder, StandardScaler,OrdinalEncoder, PowerTransformer
from sklearn.compose import ColumnTransformer 
from sklearn.pipeline import Pipeline

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()
ordinal_encoder = OrdinalEncoder()

transform_pipe = Pipeline(steps=[
    ('transformer', PowerTransformer(method='yeo-johnson'))
])

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, oh_columns),
        ("Ordinal_Encoder", ordinal_encoder, or_columns),
        ("Transformer", transform_pipe, transform_columns),
        ("StandardScaler", numeric_transformer, num_column)
    ]
)

In [25]:
X=pd.DataFrame(X)

In [65]:
X=preprocessor.fit_transform(X)
X

array([[ 0.        ,  1.        ,  0.        , ...,  0.38666657,
        -1.39853722, -0.65122993],
       [ 0.        ,  1.        ,  0.        , ..., -0.14228155,
         0.1698353 , -0.53321103],
       [ 0.        ,  1.        ,  0.        , ...,  1.69498375,
         0.91907852, -0.6748337 ],
       ...,
       [ 0.        ,  1.        ,  0.        , ..., -0.19871259,
         1.36027953,  1.63833662],
       [ 0.        ,  1.        ,  0.        , ..., -0.16387483,
         0.22150859,  2.18122353],
       [ 0.        ,  1.        ,  0.        , ..., -0.10805575,
        -0.06776315,  0.45814768]], shape=(25480, 24))

In [66]:
!pip install scikit-learn

Collecting scikit-learn

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (21.0 MB/36.5 MB, attempt 1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002081CAD1450>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/35/e5/d6d0e51fc888f692a35134336866341c08655d92614f492c6860dc45bb2c/scipy-1.17.1-cp313-cp313-win_amd64.whl

  Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\dell\miniconda3\lib\site-packages (from scikit-learn) (2.4.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.5 MB ? eta -:--:--
    --------------------------------------- 0.5/36.5 MB 1.2 MB/s eta 0:00:30
    --------------------------------------- 0.8/36.5 MB 1.1 MB/s eta 0:00:34
   - -------------------------------------- 1.0/36.5 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/36.5 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/36.5 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.6/36.5 MB 999.9 kB/s eta 0:00:35
   -- ------------------------------------- 1.8/36.5 MB 967.3 kB/s eta 0:00:36
   -- ------------------------------------- 2.1/36.5 MB 984.5 kB/s eta 0:00:35
   -- ------------------------------------- 2.4/36.5 MB 975.4 kB/s eta 0:00:36
   -- ------------------------------------- 2.4/36.5 MB 975.4 kB/s eta 0:00:36
   -- ------------------------------------- 2.6/36.5 MB 978.5 kB/s eta 0:00:35
   --- ------------------------------------ 2.9/36.5 MB 958.4 kB/s eta 0:00:36
   --- ------------------------------------ 2.9/36.5 MB 958.4 kB/s eta 0:00:36
   --- ------------------------------------ 3.1/36.5 MB 898.8 kB/s eta 0:00:38
   --- ------------------------------------ 3.1/36.5 MB 898.8 kB/s eta 0:00:38
   --- ------------------------------------ 3.4/36.5 MB 874.3 kB/s eta 0:00:38
   --- ------------------------------------ 3.4/36.5 MB 874.3 kB/s eta 0:00:38
   ---- ----------------------------------- 3.7/36.5 MB 873.4 kB/s eta 0:00:38
   ---- ----------------------------------- 3.9/36.5 MB 883.0 kB/s eta 0:00:37
   ---- ----------------------------------- 4.2/36.5 MB 898.4 kB/s eta 0:00:36
   ---- ----------------------------------- 4.5/36.5 MB 910.7 kB/s eta 0:00:36
   ----- ---------------------------------- 4.7/36.5 MB 911.6 kB/s eta 0:00:35
   ----- ---------------------------------- 5.0/36.5 MB 917.2 kB/s eta 0:00:35
   ----- ---------------------------------- 5.2/36.5 MB 919.7 kB/s eta 0:00:34
   ----- ---------------------------------- 5.2/36.5 MB 919.7 kB/s eta 0:00:34
   ------ --------------------------------- 5.5/36.5 MB 918.8 kB/s eta 0:00:34
   ------ --------------------------------- 5.8/36.5 MB 922.0 kB/s eta 0:00:34
   ------ --------------------------------- 6.0/36.5 MB 925.5 kB/s eta 0:00:33
   ------ --------------------------------- 6.3/36.5 MB 928.0 kB/s eta 0:00:33
   ------ --------------------------------- 6.3/36.5 MB 928.0 kB/s eta 0:00:33
   ------- -------------------------------- 6.6/36.5 MB 929.4 kB/s eta 0:00:33
   ------- -------------------------------- 6.8/36.5 MB 931.6 kB/s eta 0:00:32
   ------- -------------------------------- 7.1/36.5 MB 932.7 kB/s eta 0:00:32
   -------- ------------------------------- 7.3/36.5 MB 934.4 kB/s eta 0:00:32
   -------- ------------------------------- 7.3/36.5 MB 934.4 kB/s eta 0:00:32
   -------- ------------------------------- 7.6/36.5 MB 923.8 kB/s eta 0:00:32
   -------- ------------------------------- 7.9/36.5 MB 927.9 kB/s eta 0:00:31
   -------- ------------------------------- 8.1/36.5 MB 929.1 kB/s eta 0:00:31
   -------- ------------------------------- 8.1/36.5 MB 929.1 kB/s eta 0:00:31
   --------- ------------------------------ 8.4/36.5 MB 924.4 kB/s eta 0:00:31
   --------- ------------------------------ 8.7/36.5 MB 927.7 kB/s eta 0:00:31
   --------- ------------------------------ 8.9/36.5 MB 933.9 kB/s eta 0:00:30
   ---------- ----------------------------- 9.2/36.5 MB 935.2 kB/s eta 0:00:30
   ---------- ----------------------------- 9.2/36.5 MB 935.2 kB/s eta 0:00:30
   ---------- ----------------------------- 9.4/36.5 MB 934.4 kB/s eta 0:00:29
   ---------- ----------------------------- 9.7/36.5 MB 936.6 kB/s eta 0:00:29
   ---------- ----------------------------- 10.0/36.5 MB 938.0 kB/s eta 0:00:29
   ----------- ---------------------------- 10.2/36.5 MB 938.7 kB/s eta 0:00:29
   ----------- ---------------------------- 10.2/36.5 MB 938.7 kB/s eta 0:00:29
   ----------- ---------------------------- 10.5/36.5 MB 937.3 kB/s eta 0:00:28
   ----------- ---------------------------- 10.7/36.5 MB 939.6 kB/s eta 0:00:28
   ------------ --------------------------- 11.0/36.5 MB 941.0 kB/s eta 0:00:28
   ------------ --------------------------- 11.3/36.5 MB 938.7 kB/s eta 0:00:27
   ------------ --------------------------- 11.3/36.5 MB 938.7 kB/s eta 0:00:27
   ------------ --------------------------- 11.5/36.5 MB 940.7 kB/s eta 0:00:27
   ------------ --------------------------- 11.8/36.5 MB 942.2 kB/s eta 0:00:27
   ------------- -------------------------- 12.1/36.5 MB 943.1 kB/s eta 0:00:26
   ------------- -------------------------- 12.3/36.5 MB 943.4 kB/s eta 0:00:26
   ------------- -------------------------- 12.3/36.5 MB 943.4 kB/s eta 0:00:26
   ------------- -------------------------- 12.6/36.5 MB 942.7 kB/s eta 0:00:26
   -------------- ------------------------- 12.8/36.5 MB 944.1 kB/s eta 0:00:26
   -------------- ------------------------- 13.1/36.5 MB 945.0 kB/s eta 0:00:25
   -------------- ------------------------- 13.4/36.5 MB 945.8 kB/s eta 0:00:25
   -------------- ------------------------- 13.4/36.5 MB 945.8 kB/s eta 0:00:25
   -------------- ------------------------- 13.6/36.5 MB 944.9 kB/s eta 0:00:25
   --------------- ------------------------ 13.9/36.5 MB 941.4 kB/s eta 0:00:25
   --------------- ------------------------ 13.9/36.5 MB 941.4 kB/s eta 0:00:25
   --------------- ------------------------ 13.9/36.5 MB 941.4 kB/s eta 0:00:25
   --------------- ------------------------ 14.2/36.5 MB 915.8 kB/s eta 0:00:25
   --------------- ------------------------ 14.2/36.5 MB 915.8 kB/s eta 0:00:25
   --------------- ------------------------ 14.4/36.5 MB 914.2 kB/s eta 0:00:25
   ---------------- ----------------------- 14.7/36.5 MB 909.3 kB/s eta 0:00:25
   ---------------- ----------------------- 14.7/36.5 MB 909.3 kB/s eta 0:00:25
   ---------------- ----------------------- 14.9/36.5 MB 903.8 kB/s eta 0:00:24
   ---------------- ----------------------- 14.9/36.5 MB 903.8 kB/s eta 0:00:24
   ---------------- ----------------------- 15.2/36.5 MB 902.9 kB/s eta 0:00:24
   ---------------- ----------------------- 15.5/36.5 MB 903.9 kB/s eta 0:00:24
   ----------------- ---------------------- 15.7/36.5 MB 906.6 kB/s eta 0:00:23
   ----------------- ---------------------- 16.0/36.5 MB 910.5 kB/s eta 0:00:23
   ----------------- ---------------------- 16.3/36.5 MB 909.2 kB/s eta 0:00:23
   ----------------- ---------------------- 16.3/36.5 MB 909.2 kB/s eta 0:00:23
   ------------------ --------------------- 16.5/36.5 MB 910.3 kB/s eta 0:00:22
   ------------------ --------------------- 16.8/36.5 MB 911.1 kB/s eta 0:00:22
   ------------------ --------------------- 16.8/36.5 MB 911.1 kB/s eta 0:00:22
   ------------------ --------------------- 17.0/36.5 MB 906.7 kB/s eta 0:00:22
   ------------------ --------------------- 17.3/36.5 MB 907.4 kB/s eta 0:00:22
   ------------------- -------------------- 17.6/36.5 MB 909.2 kB/s eta 0:00:21
   ------------------- -------------------- 17.8/36.5 MB 912.0 kB/s eta 0:00:21
   ------------------- -------------------- 18.1/36.5 MB 914.4 kB/s eta 0:00:21
   -------------------- ------------------- 18.4/36.5 MB 914.7 kB/s eta 0:00:20
   -------------------- ------------------- 18.4/36.5 MB 914.7 kB/s eta 0:00:20
   -------------------- ------------------- 18.6/36.5 MB 915.8 kB/s eta 0:00:20
   -------------------- ------------------- 18.9/36.5 MB 916.5 kB/s eta 0:00:20
   -------------------- ------------------- 19.1/36.5 MB 915.9 kB/s eta 0:00:19
   -------------------- ------------------- 19.1/36.5 MB 915.9 kB/s eta 0:00:19
   --------------------- ------------------ 19.4/36.5 MB 909.5 kB/s eta 0:00:19
   --------------------- ------------------ 19.4/36.5 MB 909.5 kB/s eta 0:00:19
   --------------------- ------------------ 19.7/36.5 MB 902.0 kB/s eta 0:00:19
   --------------------- ------------------ 19.7/36.5 MB 902.0 kB/s eta 0:00:19
   --------------------- ------------------ 19.9/36.5 MB 899.7 kB/s eta 0:00:19
   ---------------------- ----------------- 20.2/36.5 MB 898.3 kB/s eta 0:00:19
   ---------------------- ----------------- 20.4/36.5 MB 901.7 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 20.7/36.5 MB 903.8 kB/s eta 0:00:18
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/36.5 MB 811.4 kB/s eta 0:00:20
Resuming download scipy-1.17.1-cp313-cp313-win_amd64.whl (21.0 MB/36.5 MB)
   ---------------------- ----------------- 21.0/36.5 MB ? eta -:--:--
   ---------------------- ----------------- 21.0/36.5 MB ? eta -:--:--
   ----------------------- ---------------- 21.2/36.5 MB 1.2 MB/s eta 0:00:13
   ----------------------- ---------------- 21.5/36.5 MB 1.0 MB/s eta 0:00:15
   ----------------------- ---------------- 21.5/36.5 MB 1.0 MB/s eta 0:00:15
   ----------------------- ---------------- 21.5/36.5 MB 1.0 MB/s eta 0:00:15
   ----------------------- ---------------- 21.5/36.5 MB 1.0 MB/s eta 0:00:15
   ----------------------- ---------------- 21.5/36.5 MB 1.0 MB/s eta 0:00:15
   ----------------------- ---------------- 21.5/36.5 MB 1.0 MB/s eta 0:00:15
   ----------------------- ---------------- 21.5/36.5 MB 1.0 MB/s eta 0:00:15
   ----------------------- ---------------- 21.8/36.5 MB 388.8 kB/s eta 0:00:38
   ------------------------ --------------- 22.0/36.5 MB 441.5 kB/s eta 0:00:33
   ------------------------ --------------- 22.0/36.5 MB 441.5 kB/s eta 0:00:33
   ------------------------ --------------- 22.3/36.5 MB 490.9 kB/s eta 0:00:29
   ------------------------ --------------- 22.5/36.5 MB 536.5 kB/s eta 0:00:27
   ------------------------ --------------- 22.8/36.5 MB 580.9 kB/s eta 0:00:24
   ------------------------- -------------- 23.1/36.5 MB 620.4 kB/s eta 0:00:22
   ------------------------- -------------- 23.3/36.5 MB 642.9 kB/s eta 0:00:21
   ------------------------- -------------- 23.3/36.5 MB 642.9 kB/s eta 0:00:21
   ------------------------- -------------- 23.6/36.5 MB 663.9 kB/s eta 0:00:20
   -------------------------- ------------- 23.9/36.5 MB 687.0 kB/s eta 0:00:19
   -------------------------- ------------- 24.1/36.5 MB 702.0 kB/s eta 0:00:18
   -------------------------- ------------- 24.4/36.5 MB 716.2 kB/s eta 0:00:17
   -------------------------- ------------- 24.4/36.5 MB 716.2 kB/s eta 0:00:17
   -------------------------- ------------- 24.6/36.5 MB 728.5 kB/s eta 0:00:17
   --------------------------- ------------ 24.9/36.5 MB 744.2 kB/s eta 0:00:16
   --------------------------- ------------ 25.2/36.5 MB 756.6 kB/s eta 0:00:15
   --------------------------- ------------ 25.4/36.5 MB 760.5 kB/s eta 0:00:15
   ---------------------------- ----------- 25.7/36.5 MB 769.7 kB/s eta 0:00:15
   ---------------------------- ----------- 25.7/36.5 MB 769.7 kB/s eta 0:00:15
   ---------------------------- ----------- 26.0/36.5 MB 782.0 kB/s eta 0:00:14
   ---------------------------- ----------- 26.2/36.5 MB 789.6 kB/s eta 0:00:14
   ----------------------------- ---------- 26.5/36.5 MB 796.4 kB/s eta 0:00:13
   ----------------------------- ---------- 26.7/36.5 MB 802.8 kB/s eta 0:00:13
   ----------------------------- ---------- 26.7/36.5 MB 802.8 kB/s eta 0:00:13
   ----------------------------- ---------- 27.0/36.5 MB 809.0 kB/s eta 0:00:12
   ----------------------------- ---------- 27.3/36.5 MB 815.4 kB/s eta 0:00:12
   ------------------------------ --------- 27.5/36.5 MB 820.7 kB/s eta 0:00:11
   ------------------------------ --------- 27.8/36.5 MB 824.7 kB/s eta 0:00:11
   ------------------------------ --------- 28.0/36.5 MB 830.9 kB/s eta 0:00:11
   ------------------------------ --------- 28.0/36.5 MB 830.9 kB/s eta 0:00:11
   ------------------------------- -------- 28.3/36.5 MB 835.2 kB/s eta 0:00:10
   ------------------------------- -------- 28.6/36.5 MB 838.5 kB/s eta 0:00:10
   ------------------------------- -------- 28.8/36.5 MB 837.7 kB/s eta 0:00:10
   ------------------------------- -------- 28.8/36.5 MB 837.7 kB/s eta 0:00:10
   ------------------------------- -------- 29.1/36.5 MB 840.3 kB/s eta 0:00:09
   -------------------------------- ------- 29.4/36.5 MB 845.7 kB/s eta 0:00:09
   -------------------------------- ------- 29.6/36.5 MB 852.3 kB/s eta 0:00:09
   -------------------------------- ------- 29.9/36.5 MB 853.6 kB/s eta 0:00:08
   -------------------------------- ------- 29.9/36.5 MB 853.6 kB/s eta 0:00:08
   --------------------------------- ------ 30.1/36.5 MB 853.8 kB/s eta 0:00:08
   --------------------------------- ------ 30.4/36.5 MB 857.8 kB/s eta 0:00:08

In [70]:
!python -m pip install imblearn

Collecting imblearn
  Using cached imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Collecting imbalanced-learn (from imblearn)
  Using cached imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from imbalanced-learn->imblearn) (2.2.6)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from imbalanced-learn->imblearn) (1.15.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from imbalanced-learn->imblearn) (1.7.2)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn->imblearn)
  Using cached sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from imbalanced-learn->imblearn) (1.5.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from imbalanced-learn->imblearn) (3.6.0)
Using cached imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Using cached imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Using cached sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn, imblearn

   ---------------------------------------- 0/3 [sklearn-compat]
   ---------------------------------------- 0/3 [sklearn-compat]
   ---------------------------------------- 0/3 [sklearn-compat]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ---------------------------------------- 3/3 [imblearn]

Successfully installed imbalanced-learn-0.14.1 imblearn-0.0 sklearn-compat-0.1.5

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [72]:
from imblearn.combine import SMOTETomek, SMOTEENN

# Resampling the minority class. The strategy can be changed as required.
smt = SMOTEENN(random_state=42,sampling_strategy='minority' )
# Fit the model to generate the data.
X_res, y_res = smt.fit_resample(X, Y)

In [74]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report,ConfusionMatrixDisplay, \
                            precision_score, recall_score, f1_score, roc_auc_score,roc_curve 
# from xgboost import XGBClassifier
# from catboost import CatBoostClassifier

In [80]:
def evaluate_clf(y_test, y_pred):
   return accuracy_score(y_test, y_pred),precision_score(y_test, y_pred), recall_score(y_test, y_pred), f1_score(y_test, y_pred), roc_auc_score(y_test, y_pred)

In [76]:
models = {
    "Random Forest": RandomForestClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Logistic Regression": LogisticRegression(),
     "K-Neighbors Classifier": KNeighborsClassifier(),

     "Support Vector Classifier": SVC(),
    "AdaBoost Classifier": AdaBoostClassifier()

}

In [81]:
# Create a function which can evaluate models and return a report 
from sklearn.model_selection import train_test_split
def evaluate_models(X, y, models):
    '''
    This function takes in X and y and models dictionary as input
    It splits the data into Train Test split
    Iterates through the given model dictionary and evaluates the metrics
    Returns: Dataframe which contains report of all models metrics with cost
    '''
    # separate dataset into train and test
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
    
    models_list = []
    accuracy_list = []
    auc= []
    
    for i in range(len(list(models))):
        model = list(models.values())[i]
        model.fit(X_train, y_train) # Train model

        # Make predictions
        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(X_test)

        # Training set performance
        model_train_accuracy, model_train_f1,model_train_precision,\
        model_train_recall,model_train_rocauc_score=evaluate_clf(y_train ,y_train_pred)


        # Test set performance
        model_test_accuracy,model_test_f1,model_test_precision,\
        model_test_recall,model_test_rocauc_score=evaluate_clf(y_test, y_test_pred)

        print(list(models.keys())[i])
        models_list.append(list(models.keys())[i])

        print('Model performance for Training set')
        print("- Accuracy: {:.4f}".format(model_train_accuracy))
        print('- F1 score: {:.4f}'.format(model_train_f1)) 
        print('- Precision: {:.4f}'.format(model_train_precision))
        print('- Recall: {:.4f}'.format(model_train_recall))
        print('- Roc Auc Score: {:.4f}'.format(model_train_rocauc_score))

        print('----------------------------------')

        print('Model performance for Test set')
        print('- Accuracy: {:.4f}'.format(model_test_accuracy))
        accuracy_list.append(model_test_accuracy)
        print('- F1 score: {:.4f}'.format(model_test_f1))
        print('- Precision: {:.4f}'.format(model_test_precision))
        print('- Recall: {:.4f}'.format(model_test_recall))
        print('- Roc Auc Score: {:.4f}'.format(model_test_rocauc_score))
        auc.append(model_test_rocauc_score)
        print('='*35)
        print('\n')
        
    report=pd.DataFrame(list(zip(models_list, accuracy_list)), columns=['Model Name', 'Accuracy']).sort_values(by=['Accuracy'], ascending=False)
        
    return report

In [82]:
report=evaluate_models(X_res, y_res, models)
report

Random Forest
Model performance for Training set
- Accuracy: 0.9999
- F1 score: 0.9999
- Precision: 1.0000
- Recall: 0.9999
- Roc Auc Score: 0.9999
----------------------------------
Model performance for Test set
- Accuracy: 0.9534
- F1 score: 0.9582
- Precision: 0.9556
- Recall: 0.9569
- Roc Auc Score: 0.9532
===================================


Decision Tree
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9203
- F1 score: 0.9324
- Precision: 0.9193
- Recall: 0.9258
- Roc Auc Score: 0.9204
===================================


Gradient Boosting
Model performance for Training set
- Accuracy: 0.8860
- F1 score: 0.8941
- Precision: 0.8946
- Recall: 0.8944
- Roc Auc Score: 0.8852
----------------------------------
Model performance for Test set
- Accuracy: 0.8933
- F1 score: 0.9040
- Precision: 0.8982
- Recall: 0.9011
- Roc Auc Score: 0.8929
===================================


Logistic Regression
Model performance for Training set
- Accuracy: 0.7375
- F1 score: 0.7655
- Precision: 0.7406
- Recall: 0.7528
- Roc Auc Score: 0.7373
----------------------------------
Model performance for Test set
- Accuracy: 0.7371
- F1 score: 0.7682
- Precision: 0.7362
- Recall: 0.7519
- Roc Auc Score: 0.7372
===================================


K-Neighbors Classifier
Model performance for Training set
- Accuracy: 0.9661
- F1 score: 0.9578
- Precision: 0.9804
- Recall: 0.9690
- Roc Auc Score: 0.9649
----------------------------------
Model performance for Test set
- Accuracy: 0.9411
- F1 score: 0.9331
- Precision: 0.9599
- Recall: 0.9463
- Roc Auc Score: 0.9394
===================================


Support Vector Classifier
Model performance for Training set
- Accuracy: 0.8719
- F1 score: 0.8847
- Precision: 0.8770
- Recall: 0.8808
- Roc Auc Score: 0.8714
----------------------------------
Model performance for Test set
- Accuracy: 0.8737
- F1 score: 0.8911
- Precision: 0.8732
- Recall: 0.8821
- Roc Auc Score: 0.8737
===================================


AdaBoost Classifier
Model performance for Training set
- Accuracy: 0.8503
- F1 score: 0.8617
- Precision: 0.8607
- Recall: 0.8612
- Roc Auc Score: 0.8494
----------------------------------
Model performance for Test set
- Accuracy: 0.8634
- F1 score: 0.8754
- Precision: 0.8716
- Recall: 0.8735
- Roc Auc Score: 0.8627
===================================

                  Model Name  Accuracy
0              Random Forest  0.953400
4     K-Neighbors Classifier  0.941090
1              Decision Tree  0.920281
2          Gradient Boosting  0.893318
5  Support Vector Classifier  0.873681
6        AdaBoost Classifier  0.863423
3        Logistic Regression  0.737104